arch:
  - amd64
  - ppc64le
language: node_js

node_js:
  - node
  - 12
  - 10
jobs:
 exclude:
  - arch: amd64
    node_js: node
    os: windows
  - arch: amd64
    node_js: 12
    os: windows
  - arch: amd64
    node_js: 10
    os: windows

os:
  - linux
  - windows

cache:
  directories:
    - $HOME/.npm

notifications:
  email: false
